<a href="https://colab.research.google.com/github/nehapayyur/Data-Puzzles_Exercises/blob/main/Data_Puzzles_Travel_part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Geodesics

* Let's plan our next trip together!
* For this purpose, we have gathered a list of all the world's capital cities according to https://simplemaps.com/data/world-cities

Prerequisites:
* Basic geometry and geography knowledge.
* A bit of programming experience to transform data and think of a solution.

# Part 1: Can you get the two furthest capitals on Earth? (sea level)

In [98]:
import numpy as np
import pandas as pd
from geopy import distance

In [99]:
capitals_df = pd.read_csv('https://raw.githubusercontent.com/hyperc54/data-puzzles-assets/master/features/travel/worldcapitals_light.csv')

In [100]:
capitals_df.head()

          city      lat       lng
0        Tokyo  35.6839  139.7744
1      Jakarta  -6.2146  106.8451
2       Manila  14.6000  120.9833
3        Seoul  37.5600  126.9900
4  Mexico City  19.4333  -99.1333

In [101]:
capitals_df['lat_lng'] = list(zip(capitals_df.lat, capitals_df.lng))

In [102]:
capitals_df

                  city      lat       lng                lat_lng
0                Tokyo  35.6839  139.7744    (35.6839, 139.7744)
1              Jakarta  -6.2146  106.8451    (-6.2146, 106.8451)
2               Manila  14.6000  120.9833       (14.6, 120.9833)
3                Seoul  37.5600  126.9900        (37.56, 126.99)
4          Mexico City  19.4333  -99.1333    (19.4333, -99.1333)
..                 ...      ...       ...                    ...
244          Adamstown -25.0667 -130.0833  (-25.0667, -130.0833)
245   Flying Fish Cove -10.4167  105.7167   (-10.4167, 105.7167)
246  King Edward Point -54.2833  -36.5000      (-54.2833, -36.5)
247           San Juan  18.4037  -66.0636    (18.4037, -66.0636)
248   Charlotte Amalie  18.3419  -64.9332    (18.3419, -64.9332)

[249 rows x 4 columns]

In [103]:
def city_dist(df, lat_lng_val, col):
    city_dist_list = []
    for i in range(capitals_df.shape[0]):
        dist = distance.distance(lat_lng_val, col[i]).km
        city_dist_list.append([df['city'][i], dist])
    return city_dist_list

In [104]:
capitals_df['city_dist'] = capitals_df.apply(lambda x: city_dist(capitals_df, x['lat_lng'], capitals_df['lat_lng']), axis = 1)

In [105]:
capitals_df

,city,lat,lng,lat_lng,city_dist
0,Tokyo,35.6839,139.7744,"(35.6839, 139.7744)","[[Tokyo, 0.0], [Jakarta, 5776.5849120923385], ..."
1,Jakarta,-6.2146,106.8451,"(-6.2146, 106.8451)","[[Tokyo, 5776.5849120923385], [Jakarta, 0.0], ..."
2,Manila,14.6000,120.9833,"(14.6, 120.9833)","[[Tokyo, 2995.3705557369017], [Jakarta, 2781.2..."
3,Seoul,37.5600,126.9900,"(37.56, 126.99)","[[Tokyo, 1161.3995572669535], [Jakarta, 5278.0..."
4,Mexico City,19.4333,-99.1333,"(19.4333, -99.1333)","[[Tokyo, 11317.955412471481], [Jakarta, 16859...."
...,...,...,...,...,...
244,Adamstown,-25.0667,-130.0833,"(-25.0667, -130.0833)","[[Tokyo, 11603.281717988339], [Jakarta, 12963...."
245,Flying Fish Cove,-10.4167,105.7167,"(-10.4167, 105.7167)","[[Tokyo, 6232.038698407133], [Jakarta, 481.071..."
246,King Edward Point,-54.2833,-36.5000,"(-54.2833, -36.5)","[[Tokyo, 17917.21210910489], [Jakarta, 12485.8..."
247,San Juan,18.4037,-66.0636,"(18.4037, -66.0636)","[[Tokyo, 13431.516122904755], [Jakarta, 18458...."
248,Charlotte Amalie,18.3419,-64.9332,"(18.3419, -64.9332)","[[Tokyo, 13485.915935869087], [Jakarta, 18402...."

In [106]:
def max_city_dist(city_dist_list):
  return max(city_dist_list, key=lambda x: x[1])

In [107]:
capitals_df['max_city_dist'] = capitals_df.apply(lambda x: max_city_dist(x['city_dist']), axis = 1)

In [108]:
capitals_df

,city,lat,lng,lat_lng,city_dist,max_city_dist
0,Tokyo,35.6839,139.7744,"(35.6839, 139.7744)","[[Tokyo, 0.0], [Jakarta, 5776.5849120923385], ...","[Montevideo, 18574.546394837125]"
1,Jakarta,-6.2146,106.8451,"(-6.2146, 106.8451)","[[Tokyo, 5776.5849120923385], [Jakarta, 0.0], ...","[Bogotá, 19806.29001506015]"
2,Manila,14.6000,120.9833,"(14.6, 120.9833)","[[Tokyo, 2995.3705557369017], [Jakarta, 2781.2...","[Sucre, 19196.13745220027]"
3,Seoul,37.5600,126.9900,"(37.56, 126.99)","[[Tokyo, 1161.3995572669535], [Jakarta, 5278.0...","[Montevideo, 19601.616110755836]"
4,Mexico City,19.4333,-99.1333,"(19.4333, -99.1333)","[[Tokyo, 11317.955412471481], [Jakarta, 16859....","[Port Louis, 17585.822837786636]"
...,...,...,...,...,...,...
244,Adamstown,-25.0667,-130.0833,"(-25.0667, -130.0833)","[[Tokyo, 11603.281717988339], [Jakarta, 12963....","[Doha, 19865.475389507876]"
245,Flying Fish Cove,-10.4167,105.7167,"(-10.4167, 105.7167)","[[Tokyo, 6232.038698407133], [Jakarta, 481.071...","[Oranjestad, 19510.525535766497]"
246,King Edward Point,-54.2833,-36.5000,"(-54.2833, -36.5)","[[Tokyo, 17917.21210910489], [Jakarta, 12485.8...","[Tokyo, 17917.21210910489]"
247,San Juan,18.4037,-66.0636,"(18.4037, -66.0636)","[[Tokyo, 13431.516122904755], [Jakarta, 18458....","[Flying Fish Cove, 18768.2543459477]"
248,Charlotte Amalie,18.3419,-64.9332,"(18.3419, -64.9332)","[[Tokyo, 13485.915935869087], [Jakarta, 18402....","[Flying Fish Cove, 18685.859742940465]"

In [109]:
capitals_df['max_city'] = capitals_df['max_city_dist'].str[0]
max_index = capitals_df['max_city_dist'].str[1].idxmax()

max_index

79

In [110]:
max_city1 = capitals_df['city'][79]
max_city2 = capitals_df['max_city_dist'].str[0][79]
max_dist = capitals_df['max_city_dist'].str[1][79]

print(max_city1, max_city2, max_dist)

Doha Adamstown 19865.475389507876